### ISSUE TITLE
Span tags aren't needed after switch to docsify

### ISSUE THREAD

**Issue by jnebeker** [RadiusNetworks/rspec-api_doc#9]
We're planning to switch to docsify to host our documentation markdown files, one quirk is that the `<span>` tags used in the headers of the generated docs show up in the search bar:

![image](https://user-images.githubusercontent.com/4481935/92642272-f4e2f500-f2ad-11ea-8259-e30c71cf334f.png)

https://github.com/RadiusNetworks/flybuy-documentation/pull/24#pullrequestreview-469830400

Once we make the switch to docsify we shouldn't need these `<span>` tags since the section navigation works without them on docsify and they're making the search results ugly. Unless they serve another purpose I'm missing?

https://github.com/RadiusNetworks/rspec-api_doc/blob/28bef6e033b8422b41c1b08462790e05910f18af/lib/rspec/api_doc/templates/api_doc_json_template.md.erb#L13

We could also maybe make a config option to include them or not?

**Comment by cupakromer** [comment]
The intent of the `span` tags was to add anchors to the page allowing you to link directly to a sub-section.

If this was pure HTML you'd normally add such an anchor to the `<h2>` tag directly, but due to trying to prefer markdown formatting (for better or worse) the `span` was necessary.

**Comment by cupakromer** [comment]
What happens with docsify if you add a `<code>` element to the title?

```markdown
## Some title with `sample = code` in it
```
```html
<h2>Some title with <code>sample = code</code> in it</h2>
```

Does it also struggle with showing that part of the HTML in the search bar?

**Comment by jnebeker** [comment]
I think it would include the markdown backticks but not the HTML converted `<code>` elements:

![image](https://user-images.githubusercontent.com/4481935/92935152-650c8a80-f416-11ea-841f-7f86e61ccccf.png)

So it looks like it just doesn't render any markdown in that search area.
